files:
  index: resources/views/components/ui/select/index.blade.php
  option: resources/views/components/ui/select/option.blade.php
  options: resources/views/components/ui/select/options.blade.php
  trigger: resources/views/components/ui/select/trigger.blade.php
dependencies:
  internal: [icon,text]
  helpers: [popup]
